import mongoose from 'mongoose';

// Schema definition
const detailSchema = new mongoose.Schema({
  height: {
    type: Number,
    required: true
  },
  weight: {
    type: Number,
    required: true
  },
  gender: {
    type: String,
    enum: ['male', 'female', 'other'], // Gender options
    required: true
  },
  meal_routine: {
    type: [String], // Meal routine as an array of strings (e.g., Breakfast, Lunch, Dinner)
    required: true
  },
  workout_routine: {
    type: [String], // User's own workout routine
    required: true
  },
  goal: {
    type: String,
    enum: ['lose', 'gain'],
    required: true
  },
  calories_needed: {
    type: Number,  // Calories required as per the diet plan
    required: false
  },
  diet_plan: {
    type: String,  // Diet plan generated by AI
    required: false
  },
  workout_plan: {
    type: String,  // Workout plan generated by AI
    required: false
  }
}, {
  timestamps: true // Automatically adds createdAt and updatedAt fields
});

// Model creation
const Detail = mongoose.model('Detail', detailSchema);

// Export the model
export default Detail;
